AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Koa Serverless API

Globals:
  Function:
    Timeout: 30
    MemorySize: 3008
    Runtime: nodejs18.x
    Environment:
      Variables:
        NODE_ENV: production

Resources:
  # Lambda Function
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      CodeUri: .
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        # Root path
        RootPath:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref KoaApi

        # Proxy path for all routes
        ProxyPath:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref KoaApi

  # API Gateway
  KoaApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: "2.0"
        info:
          title: !Sub "${AWS::StackName}-api"
          version: "1.0"
        paths:
          /:
            x-amazon-apigateway-any-method:
              produces:
                - application/json
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiFunction.Arn}/invocations
                responses:
                  default:
                    statusCode: "200"
                passthroughBehavior: "when_no_match"
                httpMethod: POST
                type: "aws_proxy"

          /{proxy+}:
            x-amazon-apigateway-any-method:
              produces:
                - application/json
              parameters:
                - name: proxy
                  in: path
                  required: true
                  type: string
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiFunction.Arn}/invocations
                responses:
                  default:
                    statusCode: "200"
                passthroughBehavior: "when_no_match"
                httpMethod: POST
                type: "aws_proxy"

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${KoaApi}.execute-api.${AWS::Region}.amazonaws.com/"
